#version: '3.9'

services:
  app:
    build: .
    container_name: blockchain_app
    expose:
      - "8000"
    volumes:
      - frontend_build:/app/frontend_build
      - blockchain_data:/app/backend/app/blockchain
    environment:
      - BACKEND_PORT=8000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - frontend_build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app


volumes:
  frontend_build:
  blockchain_data: